### ISSUE TITLE
Unable to save created Device

### ISSUE THREAD

**Issue by Gargosio** [aws-solutions/iot-device-simulator#41] opened 2023-08-30 04:11 UTC
I am unable to save any newly created device on the simulator's web UI, this includes even the automotive demo device.
To reproduce the error one needs to create a new device.
Kindly assist since it's getting really frustrating.
Thank you in advance

**Comment by jangidms** [comment] 2023-08-30 18:33
Hi @Gargosio 
Could you please provide below details for better understanding of the issue - 
- Solution version used. To get the version of the solution, you can look at the description of the created CloudFormation stack
- Are you deploying the latest solution version from solution home page (https://aws.amazon.com/solutions/implementations/iot-device-simulator/) or trying to deploy modified version ?
- Steps to reproduce the behavior
- Do you see any error on UI when you try to create device
- Do you see any errors in the CloudWatch Logs?
- If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**)

Thanks

**Comment by fhoueto-amz** [comment] 2023-09-07 19:31
Hi @Gargosio 
We are closing this issue as we have not received any feedback and were not able to reproduce. Please feel free to reopen or add more details if needed
Thanks

**Closed by fhoueto-amz** 2023-09-07 19:31 UTC
Labels: bug
